<?php

namespace App\Models;

use App\Events\AddedToCartable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cartable extends Model
{
    use HasFactory;

    protected $fillable = [
        'letter_id',
        'checked',
        'user_id',
    ];

    public function letter()
    {
        return $this->belongsTo(Letter::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            event(new AddedToCartable($model));
        });
    }
}
